export const SETLISTATIPORECURSO = "SETLISTATIPORECURSO";
export const SETLISTARECURSO = "SETLISTARECURSO";
export const SETFILASLISTATIPORECURSOACTIVOS="SETFILASLISTATIPORECURSOACTIVOS";
export const SETFILASLISTATIPORECURSOINACTIVOS="SETFILASLISTATIPORECURSOINACTIVOS";