export const SETLISTAESTADOS = "SETLISTAESTADOS";
export const SETLISTAPERMISOS = "SETLISTAPERMISOS";
export const SETFILASLISTAESTADOSACTIVOS="SETFILASLISTAESTADOSACTIVOS";
export const SETFILASLISTAESTADOSINACTIVOS="SETFILASLISTAESTADOSINACTIVOS";