export const SETLISTAROLES = "SETLISTAROLES";
export const SETLISTAPERMISOS = "SETLISTAPERMISOS";
export const SETFILASLISTAROLESACTIVOS="SETFILASLISTAROLESACTIVOS";
export const SETFILASLISTAROLESINACTIVOS="SETFILASLISTAROLESINACTIVOS";