export const SETLISTASERVICIOS = "SETLISTASERVICIOS";
export const SETFILASLISTASERVICIOSACTIVOS="SETFILASLISTASERVICIOSACTIVOS";
export const SETFILASLISTASERVICIOSINACTIVOS="SETFILASLISTASERVICIOSINACTIVOS";