export const SETLISTAUSUARIOS = "SETLISTAUSUARIOS";
export const SETLISTAEMPLEADOS ="SETLISTAEMPLEADOS";
export const SETLISTAROLES = "SETLISTAROLES";
export const SETFILASLISTAUSUARIOSACTIVOS="SETFILASLISTAUSUARIOSACTIVOS";
export const SETFILASLISTAUSUARIOSINACTIVOS="SETFILASLISTAUSUARIOSINACTIVOS";