export const SETLISTAUSUARIOS = "SETLISTAUSUARIOS";
export const SETFILASLISTAUSUARIOSACTIVOS="SETFILASLISTAUSUARIOSACTIVOS";
export const SETFILASLISTAUSUARIOSINACTIVOS="SETFILASLISTAUSUARIOSINACTIVOS";