export const SETLISTALOTES = "SETLISTALOTES"; 
export const SETFILASLISTALOTESACTIVOS="SETFILASLISTALOTESACTIVOS"; 
export const SETFILASLISTALOTESINACTIVOS="SETFILASLISTALOTESINACTIVOS";
export const SETLISTAHISTORIAL = "SETLISTAHISTORIAL";