export const SETLISTARECURSOS = "SETLISTARECURSOS";
export const SETFILASLISTARECURSOSACTIVOS="SETFILASLISTARECURSOSACTIVOS";
export const SETFILASLISTARECURSOSINACTIVOS="SETFILASLISTARECURSOSINACTIVOS";