export const SETLISTAExpediente = "SETLISTAExpediente";
export const SETFILASLISTAExpedienteACTIVOS="SETFILASLISTAExpedienteACTIVOS";
export const SETFILASLISTAExpedienteINACTIVOS="SETFILASLISTAExpedienteINACTIVOS";
export const SETLISTAPIEZAS = "SETLISTAPIEZAS";
export const SETFILASLISTAPIEZAS = "SETFILASLISTAPIEZAS";

