export const SETLISTADIAGNOSTICOS = "SETLISTADIAGNOSTICOS";
export const SETLISTAPIEZAS ="SETLISTAPIEZAS";
export const SETLISTAESTADOS = "SETLISTAESTADOS";
export const SETFILASLISTADIAGNOSTICOSACTIVOS="SETFILASLISTADIAGNOSTICOSACTIVOS";
export const SETFILASLISTADIAGNOSTICOSINACTIVOS="SETFILASLISTADIAGNOSTICOSINACTIVOS";