export * from './authEndpoints/apiTypes';
export * from './GestionUsuarios/apiTypes';
export * from './TipoRecurso/apiTypes';
export * from './GestionRoles/apiTypes';
export * from './expediente/apiTypes';
export * from './Insumo/apiTypes';
export * from './GestionRecurso/apiTypes';
export * from './EstimarServicios/apiTypes';
export * from './CitasPorAtender/apiTypes';
export * from './Inventarios/apiTypes';
export * from './GestionServicio/apiTypes';
export * from './GestionDiagnosticos/apiTypes';
export * from './GestionEmpleados/apiTypes';
export * from './MonitoreoCuentas/apiTypes';
export * from './CitasAgendadas/apiTypes'
export * from './Reporteria/apiTypes';